# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r:
  - bioc-release
  - bioc-devel
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start