# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r:
  - bioc-release
  - bioc-devel
services:
  - xvfb
# addons:
#   apt:
#     packages:
#       - tcl8.6-dev
#       - tk8.6-dev
# before_install:
#   - export DISPLAY=:99.0