# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r:
  - bioc-release
  - bioc-devel
addons:
  apt:
    packages:
      - tklib
before_install:
  - export DISPLAY=:99.0